### ISSUE TITLE
TODO: homepage

### ISSUE THREAD

**Issue by vladpirlog** [alexanderdx/OnlineShopDAW#6]
- [x] de eliminat/implementat favourites
- [x] de scris continut in modale
- [x] de adaugat cateva produse din fiecare categorie in viewbag, pt category list
- [x] de pus poze si text in jumbotron
- [x] de pus poze si text in promotion card
- [x] de implementat cautarea
- [x] de modificat navbarul in functie de user logat/nelogat
